### ISSUE TITLE
Feature Request: Command line argument to Load Script Group at boot

### ISSUE THREAD

**Issue by leftos** [cgtrout/MSFS-PyScriptManager#3]
I always launch this app as part of my MSFS external apps, and I always load the same script group I have created. It would be great if I could pass in a command line argument that would load that script group for me on app startup.

**Comment by cgtrout** [comment]
Hi leftos:

Not sure if you are aware but you can save your script group as "_autoplay.script_group" and it will load at startup.  I think this accomplishes what you are looking for, but let me know if this isn't the case.

Sorry about the late reply.  I thought github would give me email notifications for posted issues.

**Comment by leftos** [comment]
I wasn't aware, but that totally works for what I wanted, thank you! 

Might want to add that feature in the README? I searched for "autoplay" again just now in case I missed it in my last read-through, and I didn't find mention of it.

**Comment by cgtrout** [comment]
Sure good idea.  The initial "test" script that loads the first time gives instructions on this, but it should also be in the readme.

**Comment by leftos** [comment]
Must have missed that, then. Thanks either way, this has been awesome to use.

**Comment by leftos** [comment]
I see what happened, I had an older version that you had posted as a zip in the Fenix Discord, and never thought to grab latest from here, so I never saw the message that _autoplay was a thing, because it wasn't in the older test.py. All good now.
