### ISSUE TITLE
Bug: Remaining time displays "1 day, ..." after UTC midnight rollover

### ISSUE THREAD

**Issue by leftos** [cgtrout/MSFS-PyScriptManager#6]
Because the script adds a day to the future_time if it's "before" the current_sim_time (date notwithstanding), once the current_sim_time rolls over from 23:59:59z to 00:00:00z, the future_time is now "more than 24 hours away", so the time remaining begins with "1 day".
![Screenshot 2024-11-29 170014](https://github.com/user-attachments/assets/38d26c7c-a7ef-48c6-a652-4c19ef58c4c2)

**Comment by leftos** [comment]
My rough suggestion for this would be a `future_datetime_had_day_added` global...
```
# If future time is earlier than or equal to the current time, add 1 day to move to the next day
if future_datetime <= current_sim_datetime:
    future_datetime += timedelta(days=1)
    future_datetime_had_day_added = True
else:
    future_datetime_had_day_added = False
```
...combined with this little block in update_display...
```
if future_datetime_had_day_added and future_time is not None and get_time_to_future_seconds() >= timedelta(days=1).total_seconds():
    set_future_time_internal(last_entered_time)
```

**Comment by cgtrout** [comment]
Have not tested this but looks like a solid change.  Look at the first issue for my general thoughts on your ideas.

Thanks
